### ISSUE TITLE
Support both GetAtt types

### ISSUE THREAD

**Issue by shortjared** [trek10inc/cloudformation-schema-js-yaml#1]
`!GetAtt [Foo, Bar]` is also seemingly valid...

See https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/IAM/IAM_Users_Groups_and_Policies.yaml#L73

**Comment by hauboldj** [comment]
That is not documented but makes sense.

**Comment by shortjared** [comment]
🔥 blazing speed. nice fix
